[package]
name = "wasm-in-wasm-imports"
version = "0.1.0"
authors = ["The wasm-bindgen Developers"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.85"
js-sys = "0.3.62"
wasm-bindgen-futures = "0.4.35"
