[package]
name = "wasm-bindgen-test-macro"
version = "0.3.33"
authors = ["The wasm-bindgen Developers"]
description = "Internal testing macro for wasm-bindgen"
license = "MIT/Apache-2.0"
repository = "https://github.com/rustwasm/wasm-bindgen"
edition = "2018"

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"

[lib]
proc-macro = true
