[package]
name = "wasm-bindgen-test-macro"
version = "0.2.25"
authors = ["The wasm-bindgen Developers"]
description = "Internal testing macro for wasm-bindgen"
license = "MIT/Apache-2.0"
repository = "https://github.com/rustwasm/wasm-bindgen"

[dependencies]
proc-macro2 = "0.4"
quote = "0.6"

[lib]
proc-macro = true
