[package]
authors = ["The wasm-bindgen Developers"]
edition = "2021"
name = "wasm-in-wasm"
publish = false
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
js-sys = { path = "../../crates/js-sys" }
wasm-bindgen = { path = "../../" }
wasm-bindgen-futures = { path = "../../crates/futures" }

[lints]
workspace = true
