[package]
name = "wasm-bindgen-cli"
version = "0.2.24"
authors = ["The wasm-bindgen Developers"]
license = "MIT/Apache-2.0"
repository = "https://github.com/rustwasm/wasm-bindgen/tree/master/crates/cli"
homepage = "https://rustwasm.github.io/wasm-bindgen/"
documentation = "https://rustwasm.github.io/wasm-bindgen/"
categories = ["wasm"]
description = """
Command line interface of the `#[wasm_bindgen]` attribute and project. For more
information see https://github.com/alexcrichton/wasm-bindgen.
"""

[dependencies]
curl = "0.4.13"
docopt = "1.0"
env_logger = "0.5"
failure = "0.1.2"
log = "0.4"
parity-wasm = "0.32"
rouille = { version = "2.1.0", default-features = false }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
wasm-bindgen-cli-support = { path = "../cli-support", version = "=0.2.24" }
wasm-bindgen-shared = { path = "../shared", version = "=0.2.24" }
openssl = { version = '0.10.11', optional = true }

[features]
vendored-openssl = ['openssl/vendored']
