[package]
name = "wasm-bindgen-cli-support"
version = "0.2.22"
authors = ["The wasm-bindgen Developers"]
license = "MIT/Apache-2.0"
repository = "https://github.com/rustwasm/wasm-bindgen/tree/master/crates/cli-support"
homepage = "https://rustwasm.github.io/wasm-bindgen/"
documentation = "https://docs.rs/wasm-bindgen-cli-support"
description = """
Shared support for the wasm-bindgen-cli package, an internal dependency
"""

[dependencies]
base64 = "0.9"
failure = "0.1.2"
parity-wasm = "0.32"
serde = "1.0"
serde_json = "1.0"
tempfile = "3.0"
wasm-bindgen-shared = { path = "../shared", version = '=0.2.22' }
wasm-bindgen-wasm-interpreter = { path = "../wasm-interpreter", version = '=0.2.22' }
wasm-gc-api = "0.1.9"
