[package]
name = "webidl-tests"
version = "0.1.0"
authors = ["The wasm-bindgen Developers"]
edition = "2018"

[lib]
test = false
doctest = false
path = 'lib.rs'

[build-dependencies]
wasm-bindgen-webidl = { path = '../webidl' }
env_logger = "0.6"

[dev-dependencies]
js-sys = { path = '../js-sys' }
wasm-bindgen = { path = '../..' }
wasm-bindgen-test = { path = '../test' }

[[test]]
name = 'wasm'
path = 'main.rs'
