[package]
name = "wasm-bindgen-webidl"
version = "0.2.76"
authors = ["The wasm-bindgen Developers"]
license = "MIT/Apache-2.0"
categories = ["wasm"]
repository = "https://github.com/rustwasm/wasm-bindgen/tree/master/crates/webidl"
homepage = "https://rustwasm.github.io/wasm-bindgen/"
documentation = "https://docs.rs/wasm-bindgen"
description = """
Support for parsing WebIDL specific to wasm-bindgen
"""
edition = "2018"

[dependencies]
env_logger = "0.8.1"
anyhow = "1.0"
heck = "0.3"
log = "0.4.1"
proc-macro2 = "1.0"
quote = '1.0'
syn = { version = '1.0', features = ['full'] }
wasm-bindgen-backend = { version = "=0.2.78", path = "../backend" }
weedle = "0.12"
lazy_static = "1.0.2"
sourcefile = "0.1"
structopt = "0.3.9"
