[package]
name = "wasm-bindgen-webidl"
version = "0.2.11"
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]

[dev-dependencies]
wasm-bindgen-test-project-builder = { path = "../test-project-builder", version = '=0.2.11' }

[dependencies]
failure = "0.1"
heck = "0.3"
log = "0.4.1"
proc-macro2 = "0.4.8"
quote = '0.6'
syn = { version = '0.14', features = ['full'] }
wasm-bindgen-backend = { version = "=0.2.11", path = "../backend" }
webidl = "0.7.0"
