[package]
authors = ["The wasm-bindgen Developers"]
edition = "2021"
name = "wasm-bindgen-webidl"
publish = false
version = "0.0.0"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
env_logger = "0.11.5"
heck = "0.5"
lazy_static = "1.4.0"
log = "0.4.1"
once_cell = "1.12"
proc-macro2 = "1.0"
quote = '1.0'
sourcefile = "0.2"
syn = { version = '2.0', features = ['extra-traits', 'full'] }
wasm-bindgen-backend = { path = "../backend" }
weedle = { git = "https://github.com/rustwasm/weedle.git" }

[lints]
workspace = true
