[package]
name = "fetch"
version = "0.1.0"
authors = ["The wasm-bindgen Developers"]

[lib]
crate-type = ["cdylib"]

[dependencies]
futures = "0.1.20"
wasm-bindgen = { path = "../..", features = ["serde-serialize"]  }
js-sys = { path = "../../crates/js-sys" }
wasm-bindgen-futures = { path = "../../crates/futures" }
serde = "^1.0.59"
serde_derive = "^1.0.59"

[dependencies.web-sys]
path = "../../crates/web-sys"
features = [
  'Headers',
  'Request',
  'RequestInit',
  'RequestMode',
  'Response',
  'Window',
]
