[package]
name = "wasm-bindgen-wasm-conventions"
version = "0.2.78"
authors = ["The wasm-bindgen developers"]
license = "MIT/Apache-2.0"
repository = "https://github.com/rustwasm/wasm-bindgen/tree/master/crates/wasm-conventions"
homepage = "https://rustwasm.github.io/wasm-bindgen/"
documentation = "https://docs.rs/wasm-bindgen-wasm-conventions"
description = "Utilities for working with Wasm codegen conventions (usually established by LLVM/lld)"
edition = "2018"

[dependencies]
walrus = "0.19.0"
anyhow = "1.0"
