[package]
edition = "2018"
name = "edition-2018-test"
publish = false
version = "0.0.0"

[features]
default = ["std"]
std = [
  "wasm-bindgen/std",
  "js-sys/std",
  "wasm-bindgen-futures/std",
  "web-sys/std",
  "wasm-bindgen-test/std",
]

[dependencies]
js-sys = { path = "../../js-sys", default-features = false }
wasm-bindgen = { path = "../../../", default-features = false }
wasm-bindgen-futures = { path = "../../futures", default-features = false }
wasm-bindgen-test = { path = "../../test", default-features = false }
web-sys = { path = "../../web-sys", default-features = false }

# Pinned sub-dependencies for MSRV
bumpalo = "=3.12.0"
log = "=0.4.18"
scoped-tls = { version = "=1.0.0", optional = false }
