[package]
name = "wasm-audio-worklet"
version = "0.1.0"
edition = "2021"
rust-version = "1.56"

[lib]
crate-type = ["cdylib"]

[dependencies]
console_log = "0.2.0"
js-sys = "0.3.63"
wasm-bindgen = "0.2.86"
wasm-bindgen-futures = "0.4.36"

[dependencies.web-sys]
version = "0.3.59"
features = [
  "AudioContext",
  "AudioDestinationNode",
  "AudioWorklet",
  "AudioWorkletNode",
  "AudioWorkletNodeOptions",
  "Blob",
  "BlobPropertyBag",
  "Document",
  "Event",
  "HtmlInputElement",
  "HtmlLabelElement",
  "Url",
  "Window",
]
