[package]
authors = ["The wasm-bindgen Developers"]
edition = "2021"
name = "deno"
publish = false
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = { path = "../../" }

[lints]
workspace = true
