[package]
name = "wasm-bindgen-backend"
version = "0.2.11"
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/alexcrichton/wasm-bindgen"
homepage = "https://github.com/alexcrichton/wasm-bindgen"
documentation = "https://docs.rs/wasm-bindgen-backend"
description = """
Backend code generation of the wasm-bindgen tool
"""

[features]
spans = ["proc-macro2/nightly"]

[dependencies]
quote = '0.6'
proc-macro2 = "0.4"
wasm-bindgen-shared = { path = "../shared", version = "=0.2.11" }
syn = { version = '0.14', features = ['full', 'visit-mut'] }
serde_json = "1.0"
