[package]
name = "wasm-bindgen-backend"
version = "0.2.35"
authors = ["The wasm-bindgen Developers"]
license = "MIT/Apache-2.0"
repository = "https://github.com/rustwasm/wasm-bindgen/tree/master/crates/backend"
homepage = "https://rustwasm.github.io/wasm-bindgen/"
documentation = "https://docs.rs/wasm-bindgen-backend"
description = """
Backend code generation of the wasm-bindgen tool
"""

[features]
spans = []
extra-traits = ["syn/extra-traits"]

[dependencies]
lazy_static = "1.0.0"
log = "0.4"
proc-macro2 = "0.4.8"
quote = '0.6'
syn = { version = '0.15', features = ['full'] }
wasm-bindgen-shared = { path = "../shared", version = "=0.2.35" }
