[package]
name = "wasm-bindgen-macro"
version = "0.2.12"
authors = ["The wasm-bindgen Developers"]
license = "MIT/Apache-2.0"
repository = "https://github.com/rustwasm/wasm-bindgen/tree/master/crates/macro"
homepage = "https://rustwasm.github.io/wasm-bindgen/"
documentation = "https://docs.rs/wasm-bindgen"
description = """
Definition of the `#[wasm_bindgen]` attribute, an internal dependency
"""

[lib]
proc-macro = true

[features]
spans = ["proc-macro2/nightly", "wasm-bindgen-backend/spans"]
xxx_debug_only_print_generated_code = []

[dependencies]
syn = { version = '0.14', features = ['full'] }
quote = '0.6'
proc-macro2 = "0.4.9"
wasm-bindgen-backend = { path = "../backend", version = "=0.2.12" }
wasm-bindgen-shared = { path = "../shared", version = "=0.2.12" }
