[package]
name = "rust-webassembly-weather-reports"
description = "Weather Information System- Get the mood of your city on one click using Rust and Webassembly"
version = "0.1.1"
authors = ["Ayush <ayushmishra2005@gmail.com>"]
categories = ["wasm"]
readme = "README.md"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
chrono = "0.4.11"
reqwest = "0.10.6"
wasm-bindgen-futures = "0.4.1"
json= "*"
wasm-bindgen = "0.2.78"
gloo = "0.2.1"

[dependencies.web-sys]
version = "0.3.40"
features = ["Document", "Element", "HtmlElement", "Window"]
